### ISSUE TITLE
OpenCat

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#14]
### 软件名

OpenCat

### 类型

图形化软件

### 软件官网

https://opencat.app/

### 软件最新版本

无从获取

### 一句话描述软件主要用途

各种 AI API GUI 工具，比 AS 版多一点功能

### 软件下载链接

https://opencat.app/releases/OpenCat-2.0.1.410.dmg

### 商业模式

免费, 买断, 订阅

**Comment by ivaquero** [comment]
https://github.com/Brewforge/homebrew-chinese/pull/16
