### ISSUE TITLE
莫高设计

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#143]
### 软件名

莫高设计

### 类型

图形化软件

### 软件官网

https://mastergo.com/

### 软件最新版本

1.8.0

### 一句话描述软件主要用途

原型设计平台

### 软件下载链接

https://static.mastergo.com/plugins/desktop/macos-arm/MasterGo-1.8.0.dmg

### 商业模式

免费

**Comment by Mrered** [comment]
该软件无法获取最新的版本号

**Comment by Mrered** [comment]
eaf648a95c984b20d91a7e161118552c8c479cb8

**Comment by ivaquero** [comment]
> 该软件无法获取最新的版本号

解决了吗

**Comment by Mrered** [comment]
> > 该软件无法获取最新的版本号
> 
> 解决了吗

没有，我 skip 了，官网没有找到版本号
