### ISSUE TITLE
绿联私有云

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#153]
### 软件名

绿联私有云

### 类型

图形化软件

### 软件官网

https://www.ugnas.com/download

### 软件最新版本

5.0.0

### 一句话描述软件主要用途

绿联 NAS 官方客户端

### 软件下载链接

https://ugreen.oss-cn-shenzhen.aliyuncs.com/ugreen/mac/V5.0.0/UGREEN_Nas_v5.0.0.9670_843a0_release.dmg

### 商业模式

免费

**Comment by Mrered** [comment]
该软件版本号不方便在线提取，原因如下：

![image](https://github.com/Brewforge/homebrew-chinese/assets/34948506/cd3bbb83-fdf5-47d8-9a12-a1b9f5d7f08d)

**Comment by Mrered** [comment]
livecheck 部分我搞定了：

```ruby
  livecheck do
    url "https://www.ugnas.com/download"
    regex(/mac\/V(\d+(\.\d+)+)/i)
    strategy :page_match
  end
```

软件下载链接中的版本号尾部会不会因为每次更新而变化？这个怎么处理？

**Comment by Mrered** [comment]
89df5f3b30abdec20285d09578019ff2b62efa82

**Comment by ivaquero** [comment]
很强，可以的
