### ISSUE TITLE
BuhoNTFS

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#155]
### 软件名

BuhoNTFS

### 类型

图形化软件

### 软件官网

https://www.drbuho.com/buhontfs

### 一句话描述软件主要用途

NTFS插件

### 软件下载链接

https://www.drbuho.com/download/buhontfs.dmg

### 商业模式

买断

**Comment by Mrered** [comment]
无处获取版本号

**Comment by ivaquero** [comment]
小公司的东西，经常不规范

**Comment by Mrered** [comment]
没有多重要，暂时搁置
