### ISSUE TITLE
macOS 使用 homebrew 安装后运行服务报错

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#215]
### 请先确认：

- [ ] 我尝试附加 `--force` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。

### 描述一下错误

https://github.com/Mrered/Gobin/issues/1

### 发生错误前你运行了什么

【非错误描述，迁移 issue】

### 携带参数 `--verbose --debug` 再次运行，以获取详细输出内容

```shell
【非错误描述，迁移 issue】
```

### 运行 `brew doctor` 和 `brew config` 的输出内容

```shell
【非错误描述，迁移 issue】
```

### 运行 `brew tap` 的输出内容

```shell
【非错误描述，迁移 issue】
```

**Comment by Mrered** [comment]
> 因为 nezha 官方没有 issues，您的 github 和博客也没有任何联系方式，只能在您别的仓库提 issues 了。
> 
> 环境变量上面的正常配置，但是还是运行出错：
> 
> ```
> brew services start nezha-agent
> Bootstrap failed: 5: Input/output error
> Try re-running the command as root for richer errors.
> Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist` exited with 5.
> [15:20:03] [cost 1.375s] brew services start nezha-agent
> ```
> 
> 试过 sudo 运行、start brewforge/chinese/nezha-agent、launchctl load /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist、/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist均是一样的报错
> 
> 运行`brew services info nezha-agent`输出：
> 
> ```
> brew services info nezha-agent
> nezha-agent (homebrew.mxcl.nezha-agent)
> Running: ✘
> Loaded: ✔
> Schedulable: ✘
> [15:57:21] [cost 1.645s] brew services info nezha-agent
> ```
> 
> 使用 macbook pro m2pro，系统为最新beta 版本

原 issue 作者 @XYZliang 发布的内容

**Comment by Mrered** [comment]
@XYZliang 感觉是你的文件系统权限问题，我在 Bing 上搜到了 https://www.slingacademy.com/article/homebrew-error-bootstrap-failed-input-output/

<picture><img loading="lazy" src="https://github.com/Brewforge/homebrew-chinese/assets/34948506/50070366-8614-4faa-b607-abe5834301dc" width="50%" height="auto" alt="Homebrew Error – Bootstrap failed: 5: Input/output error"></picture>

**Comment by XYZliang** [comment]
> @XYZliang 感觉是你的文件系统权限问题，我在 Bing 上搜到了 https://www.slingacademy.com/article/homebrew-error-bootstrap-failed-input-output/
> 
> <img alt="Homebrew Error – Bootstrap failed: 5: Input/output error" width="50%" height="auto" src="https://github.com/Brewforge/homebrew-chinese/assets/34948506/50070366-8614-4faa-b607-abe5834301dc">

感谢回复，我已经尝试在 chatgpt4 的建议下检查了包括 homebrew 和 homebrew.mxcl.nezha-agent.plist 的权限，似乎并没有任何问题，并尝试了 gpt4 给出的其他解决方案，但是依旧无法解决，这使得我不得不来提交 issues

对于链接中提到的办法，我之前已经尝试过#1#2，问题依旧；#3对我来说代价太大，我几乎 80% 的包和软件都是通过 homebrew 安装，因此此方案不进行尝试；#4我并没有存在任何的防护软件，clean my mac 的任何后台监控功能也早被关闭；#5我刚刚做了尝试，依旧是不成功。

我尝试利用 brew 启动 frpc 服务，却一切正常：
```
(base) [22:24:19] [~] ❱❱❱
brew services start frpc
==> Successfully started `frpc` (label: homebrew.mxcl.frpc)
[22:24:24] [cost 0.890s] brew services start frpc
```

这一切实在是太奇怪了。。

**Comment by Mrered** [comment]
@XYZliang Homebrew Services 启动的服务，命令行标准输出都在 /opt/homebrew/var/log 但是哪吒监控正常运行时和异常运行时都没有输出，就很头大。我还不是非常熟悉，让我再找找其他有用信息。

**Comment by XYZliang** [comment]
> @XYZliang Homebrew Services 启动的服务，命令行标准输出都在 /opt/homebrew/var/log 但是哪吒监控正常运行时和异常运行时都没有输出，就很头大。我还不是非常熟悉，让我再找找其他有用信息。

是的，什么狗屁日志都不给，很烦哈哈哈

**Comment by Mrered** [comment]
> > @XYZliang Homebrew Services 启动的服务，命令行标准输出都在 /opt/homebrew/var/log 但是哪吒监控正常运行时和异常运行时都没有输出，就很头大。我还不是非常熟悉，让我再找找其他有用信息。
> 
> 是的，什么狗屁日志都不给，很烦哈哈哈

难道和获取环境变量值的过程有关？我不确定，我的代码里是这么获取值的：

https://github.com/Brewforge/homebrew-chinese/blob/115a3b9e5c3a35c01aaa9b40bcb5c50ffa10dc71/Formula/nezha-agent.rb#L18-L25

**Comment by Mrered** [comment]
我不知道如何才能更好地把变量值传给 Homebrew Services 创建的 Plist 服务启动配置，所以就想到了用环境变量。（我不是一个专业的 Coder ，可能这种做法就有问题）

**Comment by XYZliang** [comment]
> > > @XYZliang Homebrew Services 启动的服务，命令行标准输出都在 /opt/homebrew/var/log 但是哪吒监控正常运行时和异常运行时都没有输出，就很头大。我还不是非常熟悉，让我再找找其他有用信息。
> > 
> > 
> > 是的，什么狗屁日志都不给，很烦哈哈哈
> 
> 难道和获取环境变量值的过程有关？我不确定，我的代码里是这么获取值的：
> 
> https://github.com/Brewforge/homebrew-chinese/blob/115a3b9e5c3a35c01aaa9b40bcb5c50ffa10dc71/Formula/nezha-agent.rb#L18-L25

我之前检查过这个脚本，看着似乎是没有问题，没有具体了解过 homebrew 包。
但是似乎生成的 plist文件不大对劲：
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>HOMEBREW_NEZHA_AGENT_PASSWORD</key>
		<string/>
		<key>HOMEBREW_NEZHA_AGENT_SERVER</key>
		<string/>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.nezha-agent</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/nezha-agent/bin/nezha-agent</string>
		<string>--password</string>
		<string/>
		<string>--server</string>
		<string/>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

可以看到
```
<string>/opt/homebrew/opt/nezha-agent/bin/nezha-agent</string>
		<string>--password</string>
		<string/>
		<string>--server</string>
		<string/>
```
这里似乎没有正确传入前面拿的环境变量。
我还没具体进行测试，之前只是感觉这里不对劲，后面提了 issues 然后上课去了

**Comment by Mrered** [comment]
运行下面命令看看有无返回值

```sh
echo $HOMEBREW_NEZHA_AGENT_PASSWORD
echo $HOMEBREW_NEZHA_AGENT_SERVER  
```

> 你可以用 * 替代输出的隐私信息

**Comment by XYZliang** [comment]
根据 gpt4 的回复，xml 配置中不支持传递环境变量，需要重新手撸一个 sh 脚本进行包装

**Comment by XYZliang** [comment]
> 运行下面命令看看有无返回值
> 
> ```shell
> echo $HOMEBREW_NEZHA_AGENT_PASSWORD
> echo $HOMEBREW_NEZHA_AGENT_SERVER  
> ```
> 
> > 你可以用 * 替代输出的隐私信息

没问题的，是我写入zshrc 的密钥和服务器接口地址

**Comment by XYZliang** [comment]
> 根据 gpt4 的回复，xml 配置中不支持传递环境变量，需要重新手撸一个 sh 脚本进行包装

https://chat.openai.com/share/0809acd8-880b-45e1-9d38-6426902ae18f

**Comment by Mrered** [comment]
这是我的 plist 的内容

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>HOMEBREW_NEZHA_AGENT_PASSWORD</key>
		<string>******************</string>
		<key>HOMEBREW_NEZHA_AGENT_SERVER</key>
		<string>***.***.***:5555</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.nezha-agent</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/nezha-agent/bin/nezha-agent</string>
		<string>--password</string>
		<string>******************</string>
		<string>--server</string>
		<string>***.***.***:5555</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

这是我的服务运行信息

```sh
brew services info nezha-agent 

nezha-agent (homebrew.mxcl.nezha-agent)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: mrered
PID: 1872
```

**Comment by Mrered** [comment]
我使用 M1 MacBook Air 和 M2 Mac mini 都测试成功了，系统都是 14.4.1 (23E224)

**Comment by Mrered** [comment]
先睡觉，明天晚上再看，我明天白天还有好多事，抱一丝啊 @XYZliang

**Comment by XYZliang** [comment]
> 这是我的 plist 的内容
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>EnvironmentVariables</key>
> 	<dict>
> 		<key>HOMEBREW_NEZHA_AGENT_PASSWORD</key>
> 		<string>*********************</string>
> 		<key>HOMEBREW_NEZHA_AGENT_SERVER</key>
> 		<string>***.***.***:5555</string>
> 	</dict>
> 	<key>KeepAlive</key>
> 	<true/>
> 	<key>Label</key>
> 	<string>homebrew.mxcl.nezha-agent</string>
> 	<key>LimitLoadToSessionType</key>
> 	<array>
> 		<string>Aqua</string>
> 		<string>Background</string>
> 		<string>LoginWindow</string>
> 		<string>StandardIO</string>
> 		<string>System</string>
> 	</array>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/opt/homebrew/opt/nezha-agent/bin/nezha-agent</string>
> 		<string>--password</string>
> 		<string>******************</string>
> 		<string>--server</string>
> 		<string>***.***.***:5555</string>
> 	</array>
> 	<key>RunAtLoad</key>
> 	<true/>
> </dict>
> </plist>
> ```
> 
> 这是我的服务运行信息
> 
> ```shell
> brew services info nezha-agent 
> 
> nezha-agent (homebrew.mxcl.nezha-agent)
> Running: ✔
> Loaded: ✔
> Schedulable: ✘
> User: mrered
> PID: 1872
> ```

~~你没有隐藏上面环境变量中的隐私信息哈~~
那问题就出现了，生成的 plist，我这明显缺失了，系统是 14.5的 m2pro MacBook

**Comment by XYZliang** [comment]
> 先睡觉，明天晚上再看，我明天白天还有好多事，抱一丝啊 @XYZliang

不是你的问题哈哈哈，期末都忙，后面我考完试也研究下

**Comment by Mrered** [comment]
（假装隐藏了）

**Comment by Mrered** [comment]
我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：

```sh
brew services stop nezha-agent
echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
source ~/.zshrc
brew reinstall nezha-agent
brew services start nezha-agent
```

我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！

因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！

我回头改一下文档，我的问题。

**Comment by Mrered** [comment]
@XYZliang 你先测测这样能不能解决问题，可以的话我重新向 nezha 文档仓库发送拉取请求

**Comment by XYZliang** [comment]
> 我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：
> 
> ```shell
> brew services stop nezha-agent
> echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
> echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
> source ~/.zshrc
> brew reinstall nezha-agent
> brew services start nezha-agent
> ```
> 
> 我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！
> 
> 因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！
> 
> 我回头改一下文档，我的问题。

是的，我也猜到了这个问题。先更改下文档的顺序，后续的话我来试着改成使用文件加载配置，当前的方法如果需要更改密钥等配置那就麻烦咯哈哈哈，得删除生成的 plist？ 或者直接重新安装（让我个菜鸟贡献个大项目的 pr）

**Comment by Mrered** [comment]
> > 我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：
> > ```shell
> > brew services stop nezha-agent
> > echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
> > echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
> > source ~/.zshrc
> > brew reinstall nezha-agent
> > brew services start nezha-agent
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！
> > 因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！
> > 我回头改一下文档，我的问题。
> 
> 是的，我也猜到了这个问题。先更改下文档的顺序，后续的话我来试着改成使用文件加载配置，当前的方法如果需要更改密钥等配置那就麻烦咯哈哈哈，得删除生成的 plist？ 或者直接重新安装（让我个菜鸟贡献个大项目的 pr）

仅需重装即可，我已经在我的博客更新了内容：[使用 Homebrew 安装哪吒监控 Agent 服务 | 🐿️松鼠收集🌰](https://blog.mre.red/archives/install_nezha_monitoring_agent_service_with_homebrew)

没问题的话本工单就结束了。

**Comment by Mrered** [comment]
> > 我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：
> > ```shell
> > brew services stop nezha-agent
> > echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
> > echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
> > source ~/.zshrc
> > brew reinstall nezha-agent
> > brew services start nezha-agent
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！
> > 因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！
> > 我回头改一下文档，我的问题。
> 
> 是的，我也猜到了这个问题。先更改下文档的顺序，后续的话我来试着改成使用文件加载配置，当前的方法如果需要更改密钥等配置那就麻烦咯哈哈哈，得删除生成的 plist？ 或者直接重新安装（让我个菜鸟贡献个大项目的 pr）

我看了一下文档，我决定自己维护自己写的内容，不然会乱糟糟的，以后有机会你再施展拳脚吧 https://github.com/nezhahq/nezhahq.github.io/pull/69

**Comment by XYZliang** [comment]
> > > 我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：
> > > ```shell
> > > brew services stop nezha-agent
> > > echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
> > > echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
> > > source ~/.zshrc
> > > brew reinstall nezha-agent
> > > brew services start nezha-agent
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！
> > > 因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！
> > > 我回头改一下文档，我的问题。
> > 
> > 
> > 是的，我也猜到了这个问题。先更改下文档的顺序，后续的话我来试着改成使用文件加载配置，当前的方法如果需要更改密钥等配置那就麻烦咯哈哈哈，得删除生成的 plist？ 或者直接重新安装（让我个菜鸟贡献个大项目的 pr）
> 
> 我看了一下文档，我决定自己维护自己写的内容，不然会乱糟糟的，以后有机会你再施展拳脚吧 [nezhahq/nezhahq.github.io#69](https://github.com/nezhahq/nezhahq.github.io/pull/69)

哈哈哈好的

**Comment by XYZliang** [comment]
> 我刚刚因为泄漏了密钥，重装了一下，我建议你 @XYZliang 执行：
> 
> ```shell
> brew services stop nezha-agent
> echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
> echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
> source ~/.zshrc
> brew reinstall nezha-agent
> brew services start nezha-agent
> ```
> 
> 我知道问题所在了！应该先添加环境变量并 `source ~/.zshrc` ，再安装并启动服务！！！
> 
> 因为 Plist 文件在安装的一瞬间生成好后不会再变了！！！
> 
> 我回头改一下文档，我的问题。

```
(base) [09:20:45] [~] ❱❱❱
brew reinstall nezha-agent
==> Fetching brewforge/chinese/nezha-agent
==> Downloading https://github.com/nezhahq/agent/releases/download/v0.16.5/nezha-agent_darwin
Already downloaded: /Users/xyzliang/Library/Caches/Homebrew/downloads/a5cc1904975cd2ed0307ed2b2f4574dc60ffdf9e722e310e17c21916b4f987cd--nezha-agent_darwin_arm64.zip
==> Reinstalling brewforge/chinese/nezha-agent
==> Caveats
请先添加环境变量
  echo 'export HOMEBREW_NEZHA_AGENT_PASSWORD="你的密钥，在你的服务页面获取"' >> ~/.zshrc
  echo 'export HOMEBREW_NEZHA_AGENT_SERVER="你的服务器和端口，格式 your.domain:5555 "' >> ~/.zshrc
  source ~/.zshrc
再安装本命令行服务，否则会导致无法向服务配置中初始化密钥和服务器参数。

若已安装，并遇到错误，则请运行
  brew services stop nezha-agent
  brew reinstall nezha-agent
  brew services start nezha-agent

To restart brewforge/chinese/nezha-agent after an upgrade:
  brew services restart brewforge/chinese/nezha-agent
Or, if you don't want/need a background service you can just run:
  HOMEBREW_NEZHA_AGENT_PASSWORD="lYUBrOoYH08AFwfCA5" HOMEBREW_NEZHA_AGENT_SERVER="serv******ang.com:5555" /opt/homebrew/opt/nezha-agent/bin/nezha-agent --password lYUBrO*********A5 --server serve***********om:5555
==> Summary
🍺  /opt/homebrew/Cellar/nezha-agent/0.16.5: 5 files, 17.2MB, built in 2 seconds
Error: Could not remove nezha-agent backup keg! Do so manually:
  sudo rm -rf /opt/homebrew/Cellar/nezha-agent/0.16.5.reinstall
[09:20:52] [cost 5.969s] brew reinstall nezha-agent
```

```
(base) [09:20:52] [~] ❱❱❱
sudo rm -rf /opt/homebrew/Cellar/nezha-agent/0.16.5.reinstall
Password:
[09:21:27] [cost 3.637s] sudo rm -rf /opt/homebrew/Cellar/nezha-agent/0.16.5.reinstall
```

```
(base) [09:21:27] [~] ❱❱❱
brew services start nezha-agent
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist` exited with 5.
[09:21:46] [cost 0.943s] brew services start nezha-agent
```

似乎简单 reinstall 并不能解决问题，plist 文件看着正常：
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>HOMEBREW_NEZHA_AGENT_PASSWORD</key>
		<string>lYU*******wfCA5</string>
		<key>HOMEBREW_NEZHA_AGENT_SERVER</key>
		<string>ser********com:5555</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.nezha-agent</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/opt/homebrew/opt/nezha-agent/bin/nezha-agent</string>
		<string>--password</string>
		<string>lYU*********wfCA5</string>
		<string>--server</string>
		<string>servera***********8m:5555</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>

```

**Comment by Mrered** [comment]
目前只解决了安装时无法传入环境变量参数的问题，根据你提供的信息，可以看出环境变量值已经能够正确传递到 Homebrew 中。

@XYZliang 你有没有尝试过 nezha 文档里手动配置 plist 文件然后启动 nezha-agent 的方法？可以正常运行吗

**Comment by XYZliang** [comment]
> 目前只解决了安装时无法传入环境变量参数的问题，根据你提供的信息，可以看出环境变量值已经能够正确传递到 Homebrew 中。
> 
> @XYZliang 你有没有尝试过 nezha 文档里手动配置 plist 文件然后启动 nezha-agent 的方法？可以正常运行吗

刚刚尝试过了，手动配置一切 ok，服务器也正常接收到：
```
(base) [14:26:46] [~] ❱❱❱
launchctl load /Users/xyzliang/Downloads/nezha_agent.plist
[14:32:05] [cost 0.021s] launchctl load /Users/xyzliang/Downloads/nezha_agent.plist

(base) [14:32:05] [~] ❱❱❱
launchctl start nezha_agent
[14:32:12] [cost 0.020s] launchctl start nezha_agent

(base) [14:32:13] [~] ❱❱❱
launchctl list | grep nezha_agent
97650	0	nezha_agent
[14:32:19] [cost 0.022s] launchctl list | grep nezha_agent
```

**Comment by XYZliang** [comment]
经过反复测试，问题出在一下地方：
卸载时并没有连同相关服务一起进行卸载：
```
(base) [14:50:42] [~] ❱❱❱
launchctl list | grep nezha
18278	0	homebrew.mxcl.nezha-agent
[14:50:48] [cost 0.019s] launchctl list | grep nezha
```
文件`/Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist`也还存在（这个不影响，`brew services start nezha-agent`会覆盖这个文件）

这导致再重新加载`/Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist`的时候，还是跟之前一样的报错，也不知道苹果犯什么病：
```
(base) [14:46:19] [~] ❱❱❱
launchctl load /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
[14:46:28] [cost 0.017s] launchctl load /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist
```
```
(base) [14:36:54] [~] ❱❱❱
brew services start nezha-agent
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/xyzliang/Library/LaunchAgents/homebrew.mxcl.nezha-agent.plist` exited with 5.
[14:37:11] [cost 0.897s] brew services start nezha-agent
```
因此已经受到上一个 bug 影响的用户，需要
```
(base) [14:50:48] [~] ❱❱❱
launchctl stop homebrew.mxcl.nezha-agent
[14:51:09] [cost 0.025s] launchctl stop homebrew.mxcl.nezha-agent

(base) [14:51:09] [~] ❱❱❱
launchctl remove homebrew.mxcl.nezha-agent
[14:51:15] [cost 0.016s] launchctl remove homebrew.mxcl.nezha-agent
```
后在 reinstall，这时候就没问题了
```
(base) [14:52:48] [~] ❱❱❱
brew services start nezha-agent
==> Successfully started `nezha-agent` (label: homebrew.mxcl.nezha-agent)
[14:53:05] [cost 0.896s] brew services start nezha-agent
```
在卸载的时候也要调用 brew service 进行停止和删除？否则可能下次开机前nezha-agent文件实际上还在，服务就还在运行？个人粗略理解，对这些不是很了解。

**Comment by XYZliang** [comment]
使用环境变量还是存在很大问题，如果需要修改配置，必须重新安装，我试着删除服务后重新`brew services start nezha-agent`是不生效的

**Comment by Mrered** [comment]
> 使用环境变量还是存在很大问题，如果需要修改配置，必须重新安装，我试着删除服务后重新`brew services start nezha-agent`是不生效的

我参考这部分 [Formula Cookbook | service block methods](https://docs.brew.sh/Formula-Cookbook#service-block-methods) 创作了 https://github.com/Brewforge/homebrew-chinese/blob/45812fd30ff2d7634863bf18c231423b9607f137/Formula/nezha-agent.rb#L18-L25

目前我这里运行正常，没有任何报错信息

```sh
❯ brew services info nezha-agent
nezha-agent (homebrew.mxcl.nezha-agent)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: mrered
PID: 1090
```

如果 @XYZliang 你有更好的向 Homebrew Service 传递参数的方式，可以直接对本仓库发起拉取请求。

就目前的测试情况，暂未发现因本仓库代码引起的错误，如有更多信息和疑问，请重新开启本工单。
