### ISSUE TITLE
pkg 缺少 uninstall 导致 CI 失败

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#219]
https://github.com/Brewforge/homebrew-chinese/blob/1cc23ba8ce844b0471d82e36f91b3a3f10d991be/Casks/squirrel-ime.rb#L21

https://github.com/Brewforge/homebrew-chinese/actions/runs/8980529305/job/24695507006#step:5:328

**Comment by ivaquero** [comment]
我晚上回去搞搞

**Comment by ivaquero** [comment]
这个过了，但是绿联的那个不行，我本地没问题

**Comment by ivaquero** [comment]
```console
Error: ugreennas: Unable to get versions
parallel: This job failed:
./.github/actions/bump-casks/script.sh brewforge/chinese/ugreennas
```
