### ISSUE TITLE
alist-cli 因不明原因导致 CI 失败

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#220]
https://github.com/Brewforge/homebrew-chinese/blob/90cf98e640e29af926cd4a571470340dd652a984/Formula/alist-cli.rb#L1-L32

https://github.com/Brewforge/homebrew-chinese/actions/runs/8980529305/job/24696237054#step:5:32

**Comment by ivaquero** [comment]
搞不清楚，先跳过了

**Comment by Mrered** [comment]
暂不予修复
