### ISSUE TITLE
哪吒监控 Dashboard

### ISSUE THREAD

**Issue by uubulb** [Brewforge/homebrew-chinese#240]
### 软件名

Nezha Dashboard

### 类型

命令行软件

### 软件官网

https://nezha.wiki/

### 软件最新版本

0.16.23

### 一句话描述软件主要用途

Self-hosted, lightweight server and website monitoring and O&M tool

### 软件下载链接

https://github.com/naiba/nezha

### 商业模式

免费

**Comment by uubulb** [comment]
Since the official installation script of Nezha has supported macOS recently (only Agent), and Agent itself has builtin support for generating launchd plist now, it seems adding a packaging script of Nezha Dashboard could be proven more useful.
The challenge is maintaining a macOS build of Nezha Dashboard, since it's not in the release.

**Comment by ivaquero** [comment]
看了看，不知道从哪下手

**Comment by Mrered** [comment]
@uubulb 你好，macOS 使用 Homebrew 安装 Nezha Agent 的方法是我创建的，因为 Nezha Agent 是一个二进制文件，方便开发出对应的 Homebrew 安装方式，目前要适配 Nezha Dashboard 的话，需要花一定的时间研究一下面板端手动安装的具体过程。我会在有进展时继续跟进该工单。
