### ISSUE TITLE
夸克网盘对应安装包已经过期

### ISSUE THREAD

**Issue by cnderrick** [Brewforge/homebrew-chinese#317]
### 请先确认：

- [ ] 我尝试附加 `--force` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。

### 描述一下错误

安装夸克网盘，报错

xxxxx@MacBook-Pro  ~  brew install --cask brewforge/chinese/quarkclouddrive
==> Downloading https://pdds.quark.cn/download/stfile//QuarkCloudDrive_v3.2.6_re
curl: (56) The requested URL returned error: 500

Error: Download failed on Cask 'quarkclouddrive' with message: Download failed: https://pdds.quark.cn/download/stfile//QuarkCloudDrive_v3.2.6_release_(Build1778677-20240516190028).dmg

原因是该地址对应的包不存在。
最新地址为：https://pdds.quark.cn/download/stfile/aagebhaggabeacich/QuarkCloudDrive_v3.7.0_release2_(Build1866534-20240801152127).dmg

### 发生错误前你运行了什么

-

### 携带参数 `--verbose --debug` 再次运行，以获取详细输出内容

```shell
-
```

### 运行 `brew doctor` 和 `brew config` 的输出内容

```shell
-
```

### 运行 `brew tap` 的输出内容

```shell
-
```

**Comment by ivaquero** [comment]
已更新 @cnderrick
