### ISSUE TITLE
夸克网盘

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#34]
### 软件名

夸克网盘

### 类型

图形化软件

### 软件官网

https://pan.quark.cn/

### 软件最新版本

3.0.7

### 一句话描述软件主要用途

夸克网盘客户端

### 软件下载链接

动态下载链接，难以获取固定连接

### 商业模式

免费, 订阅

**Comment by ivaquero** [comment]
livecheck 搞不定，弄了个 demo 放在了 experimental

**Comment by Liuxunliuxun5** [comment]
老哥你这个需要会员吗？

**Comment by Mrered** [comment]
> 老哥你这个需要会员吗？

你不会是要兜售会员吧（害怕

我有 88vip 送的
