### ISSUE TITLE
keyviz中文版

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#379]
### 软件名

keyviz-cn

### 类型

图形化软件

### 软件官网

https://github.com/zetaloop/keyviz

### 软件最新版本

2.0.0a2

### 一句话描述软件主要用途

优雅地显示按下的按键，录屏有用

### 软件下载链接

https://github.com/zetaloop/keyviz/releases/download/v2.0.0a2/keyviz-v2.0.0a2-macos.dmg

### 商业模式

免费

**Comment by ivaquero** [comment]
可以参考 https://github.com/Brewforge/homebrew-extras/blob/main/Casks/k/keyviz.rb

**Comment by ivaquero** [comment]
搞定
