### ISSUE TITLE
Action 里的 HOMEBREW_GITHUB_API_TOKEN 过期

### ISSUE THREAD

**Issue by Oscaner** [Brewforge/homebrew-chinese#38]
### 请先确认：

- [ ] 我尝试附加 `--force` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
- [ ] 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。

### 描述一下错误

HOMEBREW_GITHUB_API_TOKEN 过期

### 发生错误前你运行了什么

无

### 携带参数 `--verbose --debug` 再次运行，以获取详细输出内容

```shell
无
```

### 运行 `brew doctor` 和 `brew config` 的输出内容

```shell
无
```

### 运行 `brew tap` 的输出内容

```shell
无
```

**Comment by Oscaner** [comment]
<img width="631" alt="image" src="https://github.com/Brewforge/homebrew-chinese/assets/26829325/bd1a150a-9353-44fa-8f0d-83caeae19afe">

**Comment by Oscaner** [comment]
已经更新成我的 PAT 了

**Comment by ivaquero** [comment]
谢谢，单位不让上网，刚看到
