### ISSUE TITLE
夜神模拟器

### ISSUE THREAD

**Issue by Oscaner** [Brewforge/homebrew-chinese#466]
### 软件名

夜神模拟器

### 类型

图形化软件

### 软件官网

https://www.yeshen.com/

### 一句话描述软件主要用途

夜神模拟器，电脑玩手游的神兵利器

### 商业模式

免费

**Comment by ivaquero** [comment]
@Oscaner 这个软件最后一次更新是大约2年前

**Comment by Oscaner** [comment]
@ivaquero 对，我看到了，而且 brew 官方仓库也有。
https://formulae.brew.sh/cask/noxappplayer#default

**Comment by ivaquero** [comment]
好吧
