### ISSUE TITLE
mihomo-party

### ISSUE THREAD

**Issue by Oscaner** [Brewforge/homebrew-chinese#481]
### 软件名

mihomo-party

### 类型

图形化软件

### 软件官网

https://github.com/mihomo-party-org/mihomo-party

### 一句话描述软件主要用途

一个更易用的代理客户端

### 商业模式

免费

**Comment by ivaquero** [comment]
@Oscaner 这个和其他的代理相比有哪些优势呢？

我目前没考虑 catalina 及其之前的系统

**Comment by Oscaner** [comment]
> @Oscaner 这个和其他的代理相比有哪些优势呢？
> 
> 我目前没考虑 catalina 及其之前的系统

我也不是很清楚。我朋友跟我说是 clash 客户端不维护了，这个是社区接手的项目😂

**Comment by ivaquero** [comment]
哦，接手的项目好几个，有 
- tauri: clash-verge-rev，clash-nyanpasu
- flutter: flclash，hiddify
- 。。。
