### ISSUE TITLE
CI 崩了

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-chinese#49]
### 请先确认：

- [X] 我尝试附加 `--force` 后重新运行了终端的代码。
- [X] 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
- [X] 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。

### 描述一下错误

@Oscaner 大佬麻烦看看， CI 崩了

### 发生错误前你运行了什么

null

### 携带参数 `--verbose --debug` 再次运行，以获取详细输出内容

```shell
null
```

### 运行 `brew doctor` 和 `brew config` 的输出内容

```shell
null
```

### 运行 `brew tap` 的输出内容

```shell
null
```

**Comment by Oscaner** [comment]
Let me check.

**Comment by Oscaner** [comment]
Fixed.

**Comment by Oscaner** [comment]
Link https://github.com/Brewforge/homebrew-chinese/issues/59
