### ISSUE TITLE
Action 改进

### ISSUE THREAD

**Issue by Oscaner** [Brewforge/homebrew-chinese#59]
### 请先确认：

- [X] 我尝试附加 `--force` 后重新运行了终端的代码。
- [X] 我尝试运行 `brew update-reset` 和 `brew update` 后重新运行了终端的代码。
- [X] 我尝试运行 `brew doctor` 并依照提示执行修复指令后重新运行了终端的代码。

### 描述一下错误

- [x] 关闭 PR 和 Push 上的 bump-pr 执行，这会导致大量无意义的 bump-pr 报错 
  (想要手动执行 bump-pr 可以到 Actions - schedule 选择 branch 手动执行)
- [x] bump-pr 由每日 schedule 定期执行，检查软件更新
- [x] 修复已存在的 livecheck 错误，如 `Unable to get versions`
- [x] 为 PR 和 Push 创建 aduit action，仅执行 brew 检查命令，确保 `.rb` 文件符合 brew 规范
  - [x] brew audit
  - [x] brew livecheck
  - [x] brew bump-cask-pr --dry-run
  - [x] brew bump-formula-pr --dry-run

**Comment by ivaquero** [comment]
感谢

**Comment by Oscaner** [comment]
@ivaquero @Mrered 你们能找到这个 4.5.4 是什么问题么？或者 livecheck 有没有其他方案，不采用他们的 xml
https://github.com/Brewforge/homebrew-chinese/actions/runs/8105943805/job/22155094779#step:5:104
<img width="567" alt="image" src="https://github.com/Brewforge/homebrew-chinese/assets/26829325/5e8e38e1-a8d8-4ee9-bc72-301dcaec7c44">

**Comment by ivaquero** [comment]
我看了xml，是最新版本，但不确定这个为啥会check低版本，一个粗暴的方法是，采用法语助手的xml，他们都是一个公司，版本号同步的产品

**Comment by ivaquero** [comment]
https://github.com/Homebrew/homebrew-cask/pull/167579

这个里面的修改或许可以修复这个问题

**Comment by ivaquero** [comment]
@Oscaner 非常感谢！

**Comment by Oscaner** [comment]
All done. Let me close.
